version: '3'

services:
    api:
      build:
        dockerfile: ./Dockerfile
        context: .
      ports:
        - "3000:3000"
      # command: ["npm","run","migration:run"]
      # command: npm run migration:run